[package]
name = "rls-vfs"
version = "0.4.5"
authors = ["Nick Cameron <ncameron@mozilla.com>"]
description = "Virtual File System for the RLS"
license = "Apache-2.0/MIT"
repository = "https://github.com/nrc/rls-vfs"
categories = ["development-tools"]

[dependencies]
rls-span = "0.4"

[features]
racer-impls = []
